### ISSUE TITLE
Neo4jModelParser.getRelationshipType() returns wrong relationship for Gene & Chromosome

### ISSUE THREAD

**Issue by yasharmaster** [intermine/neo4j#95]
`Neo4jModelParser.getRelationshipType("Gene", "Chromosome")` returns `"Chromosome"` while it should return `"LOCATED_ON"`.

@sammyjava

**Comment by sammyjava** [comment]
Actually, chromosome references should be ignored since they are redundant with chromosomeLocation, which should be loaded as a LOCATED_ON relationship.

**Comment by sammyjava** [comment]
SequenceFeature.chromosome is indeed ignored
[https://github.com/intermine/neo4j/blob/dev/intermine-neo4j/src/main/resources/preview-genomic_model-neo4j.xml#L96](https://github.com/intermine/neo4j/blob/dev/intermine-neo4j/src/main/resources/preview-genomic_model-neo4j.xml#L96)
as is chromosomeLocation, since that should be explicitly loaded by Neo4jEdgeLoader.

Let me know if there's still something messed up given all that. I haven't run the edge loader for a while.

**Comment by yasharmaster** [comment]
@sammyjava , the relationship between Gene and Chromosome is indeed loaded in Neo4j as LOCATED_ON. I have checked it by running the following Cypher.
```
MATCH (n:Gene)-[r]-(m:Chromosome)
RETURN DISTINCT type(r)
```
The above query returns `"LOCATED_ON"` as the output.

But `Neo4jModelParser.getRelationshipType` is not returning "LOCATED_ON" when Gene & Chromosome are passed as parameter. I have checked it by running.
```
Neo4jLoaderProperties props = new Neo4jLoaderProperties();
Neo4jModelParser parser = new Neo4jModelParser();
parser.process(props);

System.out.println(parser.getRelationshipType("Gene", "Chromosome"));
/*
    Output - Chromosome
 */

System.out.println(parser.getRelationshipType("SequenceFeature", "Chromosome"));
/*
    Output - Chromosome
 */

System.out.println(parser.getRelationshipType("Chromosome", "Gene"));
/*
    Output - Gene
 */

System.out.println(parser.getRelationshipType("Chromosome", "SequenceFeature"));
/*
    Output - SequenceFeature
 */
```

**Comment by sammyjava** [comment]
OK I'll clear that up when I get back to work on Thursday.

**Comment by sammyjava** [comment]
I still need to check through the response when a class is actually treated as a relationship (Location is the main example, stored not as :Location but as a LOCATED_ON edge); but I noticed that you're calling getRelationshipType(String, String) wrong. The first string is a class name, so upper case; the second string is the FIELD name, so lower case. Examples: ("Gene", "chromosomeLocation"), ("Author", "publications"), etc. That will make a big difference. :)

The output currently fails with defaults, which may not be desired, since it confused you:
```
$ ./gradlew modelParser -PArgs=src/main/resources/preview-genomic_model-neo4j.xml,Gene.Chromosome
Gene.Chromosome --> Chromosome
```
Gene has no field called "Chromosome" so perhaps that should respond differently.

Then, if I call it correctly, I get:
```
$ ./gradlew modelParser -PArgs=src/main/resources/preview-genomic_model-neo4j.xml,Gene.chromosome
Gene.chromosome --> chromosome
```
which is ALSO misleading since SequenceFeature.chromosome is NOT being stored in the graph. It's redundant: we get the chromosome via chromosomeLocation, so I don't store it:
```
<class name="SequenceFeature" extends="BioEntity" is-interface="true" neo4j-ignore="true">
        <reference name="chromosome" referenced-type="Chromosome" neo4j-ignore="true"/>
        <reference name="chromosomeLocation" referenced-type="Location" neo4j-ignore="true"/>
</class>
```
Finally, you'll note that chromosomeLocation is also ignored, but in this case it's because I explicitly load classes-as-relationships with Neo4jEdgeLoader using command-line instructions. That results in the incorrect result:
```
$ ./gradlew modelParser -PArgs=src/main/resources/preview-genomic_model-neo4j.xml,Gene.chromosomeLocation
Gene.chromosomeLocation --> chromosomeLocation
```
So I'll try to get all that straightened out. Basically, I need to put something into the XML file to instruct Neo4jEdgeLoader which classes-as-edges to load, rather than depending on the command line, and then that info gets used by Neo4jModelParser to return accurate getRelationshipType() results.

**Comment by yasharmaster** [comment]
@sammyjava Thanks for pointing it out. I will use lower case strings for "field name" while testing getRelationshipType method from now on. :smile:

**Comment by sammyjava** [comment]
This is fixed, by adding two new attributes to the XML file: neo4j-as-relationship flags a class to be loaded as a Neo4j relationship, not node; neo4j-relationship-target flags the target of that particular relationship. For example:
```
<class name="Location" is-interface="true" neo4j-as-relationship="true">
	<attribute name="start" type="java.lang.Integer"/>
	<attribute name="end" type="java.lang.Integer"/>
	<attribute name="strand" type="java.lang.String"/>
	<reference name="locatedOn" referenced-type="BioEntity" reverse-reference="locatedFeatures" neo4j-relationship="LOCATED_ON" neo4j-relationship-target="true"/>
	<reference name="feature" referenced-type="BioEntity" reverse-reference="locations" neo4j-ignore="true"/>
	<collection name="dataSets" referenced-type="DataSet" neo4j-ignore="true"/>
</class>
```
So, to convert a query on Gene.chromosomeLocation do the following:

1. Determine that **Gene**.chromosomeLocation references _Location_ 
2. Neo4jModelParser.isRelationship("Location") returns true, telling you it's _stored as a relationship_
3. Neo4jModelParser.getRelationshipTarget(Location) returns _locatedOn_
4. Neo4jModelParser.getRelationshipType("Location", "locatedOn") returns **LOCATED_ON**
5. Determine that Location.locatedOn references **BioEntity**

leading to the Cypher query
```
(:Gene)-[:LOCATED_ON]->[:BioEntity]
```
This is now implemented in Neo4jEdgeLoader which now simply takes the name of a Class.field:
```
$ ./gradlew edgeLoader -PArgs=Gene.chromosomeLocation
sourceClass=Gene
targetName=locatedOn
relationshipType=LOCATED_ON
targetClass=BioEntity
chromosomeLocation:[strand, start, end, id]
(Gene:1014323)-[LOCATED_ON:3552285]->(BioEntity:1000106)
(Gene:1014326)-[LOCATED_ON:1404159]->(BioEntity:1000094)
 ```

**Comment by yasharmaster** [comment]
@sammyjava Thanks for the update Sam. I will make required updates to QueryGenerator soon.
BTW since SequenceFeature.chromosome is not being stored in the graph, how do I handle Path Queries which involve `Gene.chromosome` path. For example,
```
<query model="genomic" view="Gene.primaryIdentifier Gene.chromosome.primaryIdentifier">
</query>
```
`getRelationshipType` for `Gene.chromosome` is giving same output as before.
```
Task -
./gradlew modelParser -PArgs=src/main/resources/preview-genomic_model-neo4j.xml,Gene.chromosome
Output - 
Gene.chromosome --> chromosome
```

**Comment by sammyjava** [comment]
Oh, yeah, I forgot about that, yet a different problem: Gene.chromosome isn't stored in the graph since we have it as Gene-[LOCATED_ON]->[:BioEntity:Chromosome] which came from Gene.chromosomeLocation. I'll create a new issue for this one, which results from querying on references and collections which are ignored in Neo4j loading because they are redundant and handled elsewhere in the data model.
